### ISSUE TITLE
Terminology: Black Magic Debug App or Black Magic App

### ISSUE THREAD

**Issue by lenvm** [blackmagic-debug/black-magic-org#16]
On the [index page](https://black-magic.org/) of the website the Black Magic Debug App (BMDA) is mentioned. On the [terminology page](https://black-magic.org/knowledge/terminology.html) Black Magic App is used.

Similarly, the index page mentions Black Magic Debug firmware, whereas the terminology page defines Black Magic Firmware (BMF).

Using different terminology in different places is not consistent. Which of the two is the preferred terminology?

If you let me know I can create a pull request to update the respective pages.

**Comment by dragonmux** [comment]
From the conversation we had with @esden about this, generally speaking the "Debug" part is optional but always allowed. It might be best to convey that on the terminology page as both "BMA" and "BMDA" are valid (referring to exactly the same thing), we just happen to prefer "BMDA".

Agreed that consistency is important, so perhaps lets use BMDA, BMDF, etc, on the website and talk about the allowance to drop the D in the initialism on the terminology page

**Comment by esden** [comment]
Agreed, I think we should extend the terminology page to include the fact that "Debug" is optional. I tend to use BMP, BMA and BMF, whereas @dragonmux tends to use BMDA and BMDA abbreviations. In both cases it is still clear what elements of the system are meant.
