### ISSUE TITLE
404: Not Found error during local previewing

### ISSUE THREAD

**Issue by lenvm** [blackmagic-debug/black-magic-org#17]
Following the instructions in the readme, I am able to run the script `./run_livereload.py` within the `env` environment.

The output is:
```
[I yymmdd hh:mm:ss server:335] Serving on http://127.0.0.1:5500
[I yymmdd hh:mm:ss handlers:62] Start watching changes
[I yymmdd hh:mm:ss handlers:64] Start detecting changes
```

Once I visit http://127.0.0.1:5500/, an extra row is added to the output:
```
[W yymmdd hh:mm:ss web:2344] 404 GET / (127.0.0.1) 1.11ms
```

And the page displays:
404: Not Found

Can you help me figure out what is causing this 404 error?

I'm using:
- MacOS 13.3.1 on Apple Silicon
- Python 3.11.3

**Comment by esden** [comment]
I think I found out what the issue might be. You need to run a sphinx page build one time before starting livereload server.

`make html` should do the trick. After that you should be able to launch livereload.

Let me know if that helps, I will update the README to mention that.

**Comment by esden** [comment]
When playing with this I also noticed that you will need to install the following brew packages:
```
brew install cairo
brew install pango
brew install python-tk@3.11
```
Otherwise the pinout diagrams can't be generated.

**Comment by lenvm** [comment]
Hi @esden, thanks for looking into this and providing the information, this was really helpful.

Indeed, running `make html` once before `python ./run_livereload.py` the pages are seen. During `make html` some warnings about the generation of the diagrams were seen.

After installing the mentioned brew packages in the virtual environment and running `make html` again, I was also able to see the diagrams.

One problem I encountered is an `OSError: [Errno 48] Address already in use`, which occurs when stopping the livereload script using `CTRL + Z`, and afterwards trying to start the server again using `python ./run_livereload.py`.

The full output is:
```bash
[I yymmdd hh:mm:ss server:335] Serving on http://127.0.0.1:5500
Traceback (most recent call last):
  File "/repo/./run_livereload.py", line 12, in <module>
    server.serve(root='_build/html')
  File "/repo/env/lib/python3.11/site-packages/livereload/server.py", line 339, in serve
    self.application(
  File "/repo/env/lib/python3.11/site-packages/livereload/server.py", line 291, in application
    app.listen(port, address=host)
  File "/repo/env/lib/python3.11/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/repo/env/lib/python3.11/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
              ^^^^^^^^^^^^^
  File "/repo/env/lib/python3.11/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
```

Is there a better way to stop the `run_livereload.py` script than using `CTRL + Z`, such that it closes/shuts down the socket when the user wants to stop the livereload server?

**Comment by esden** [comment]
CTRL-Z suspends and sends the process to the background and does not stop the process. You need to use CTRL-C instead if you want to shut down the process. If the other process is suspended it will keep the socket asserted.

**Comment by lenvm** [comment]
Ah yes, thanks!
